### ISSUE TITLE
Update lesson setup for the learners

### ISSUE THREAD

**Issue by gcroci2** [esciencecenter-digital-skills/medical-image-processing#10]
We can do this as a last step when we will have all episodes and images we want to use in the lesson.

- Depending (also) on how big the images are, we need to decide where to make them available for future students. 
- We need to add instructions in the [setup section](https://github.com/esciencecenter-digital-skills/medical-image-processing/blob/main/learners/setup.md) about how to obtain them, and how to setup the environment for the lesson

**Comment by drcandacemakedamoore** [comment]
I started the setup with some notes on the environment and added a draft pull request for you

**Comment by gcroci2** [comment]
I will build up on the draft you created
