### ISSUE TITLE
make a survey/test for admitting students without image processing

### ISSUE THREAD

**Issue by gcroci2** [esciencecenter-digital-skills/medical-image-processing#23]
A first draft:

# Medical image processing workshop readiness survey

This survey aims to assess your basic knowledge to ensure you are prepared for the upcoming workshop. Please answer the following questions honestly.

## Section 1: Basic information

1. Create an identifier code, by combining the day on which you were born (two digits) with the first two letters of the street you live on (two letters), and the last two digits of your phone number. This allows us to link your pre-workshop survey results to your post-workshop survey results, while ensuring your anonymity.Example: if you were born on the 6th, live on Schoolstraat, and your phone number is 0123456789, your code is 06SC89. (Q1 from [here](https://www.surveymonkey.com/results/SM-02cWu9655dDHrxija1zwrg_3D_3D/))
2. What is the name of the faculty you work at in your institute? (for example: Law, Humanities, Medicine, see Q2 from [here](https://www.surveymonkey.com/results/SM-02cWu9655dDHrxija1zwrg_3D_3D/))
3. What is your current level of study? (Multiple choice: Undergraduate, Master's, Ph.D., Other - please specify)
5. What is your field of study? (Short answer)
6. How did you hear about this workshop? (Multiple Choice: University announcement, Social media, Friend/colleague, Other - please specify)

## Section 2: Background knowledge

6. Do you have any prior experience with image processing or will you have taken the Image Processing in Python workshop before this workshop? (Yes/No)
If yes, please describe your experience. (Short Answer)
7. Which programming languages are you familiar with? (Select all that apply: Python, MATLAB, C++, Java, Other - please specify)
8. Have you taken any courses related to medical imaging? (Yes/No)
If yes, please list the courses. (Short Answer)

## Section 3: Technical knowledge assessment

9. Which of the following libraries used to read images in Python do you have experience with, or have you used before? (Select all that apply: OpenCV, PIL/Pillow, scikit-image, imageio, None of the above)
10. How would you rate your understanding of how an image is represented in programming (e.g., as a matrix of pixels)? (Multiple Choice: Excellent, good, fair, poor, no understanding)
11. Have you ever manipulated images in programming, such as resizing, rotating, or cropping? (Yes/No)
If yes, please describe what you have done. (Short Answer)
12. Do you have experience creating image masks for processing tasks? (Yes/No)
13. Have you performed bitwise operations on images, such as AND, OR, NOT, or XOR? (Yes/No)
14. How comfortable are you with generating and interpreting image histograms? (Multiple Choice: Very comfortable, Comfortable, Somewhat comfortable, Not comfortable at all)
15. Which image filters have you used for tasks like blurring, sharpening, or edge detection? (Select all that apply: Gaussian Blur, Median Filter, Sobel Filter, Laplacian Filter, None of the above)

## Section 4: Additional skills

16. Do you have experience with any medical image processing software? (Yes/No)
If yes, please specify the software. (Short Answer)
17. Are you comfortable working with large datasets? (Yes/No)
18. Do you have any experience with machine learning or AI in the context of image processing? (Yes/No)
If yes, please describe your experience. (Short Answer)

## Section 5: Workshop Expectations

19. Why do you want to participate in this workshop? (Multiple choice, take inspiration from Q15 from [here](https://www.surveymonkey.com/results/SM-02cWu9655dDHrxija1zwrg_3D_3D/) for the answers)
20. What do you hope to learn in this workshop? (Q16 from [here](https://www.surveymonkey.com/results/SM-02cWu9655dDHrxija1zwrg_3D_3D/))

**Comment by drcandacemakedamoore** [comment]
I just added a change to the question to cover people who will take the Image processing in Python course beforehand. Besides that I think we are good @gcroci2

**Comment by gcroci2** [comment]
How should we proceed about this? Did you have a tool already in mind to send this out? @drcandacemakedamoore

**Comment by drcandacemakedamoore** [comment]
Sacha has recommended we use Microsoft Forms, so I made this survey that way. When it actually goes out I will move the item to done.

**Comment by drcandacemakedamoore** [comment]
I'm testing the test/quiz on my team-mates today. I'll send it to you as
well.
